## Exercise 7

Increasing the size of the training set seems to lead to a higher percentage of correction for the Multi-Layered Perceptron Neural Network, as indicated below

    200:   69.0% Correct
    1000:  75.0% Correct
    5000:  79.9% Correct


In [4]:
import pylab as pl
import numpy as np
import mlp
import cPickle, gzip

# Read the dataset in (code from sheet)
f = gzip.open('mnist.pkl.gz','rb')
tset, vset, teset = cPickle.load(f)
f.close()

nread = [200, 500, 1000]
for k in range(len(nread)):
    #nread = nread[k]
    # Just use the first few images
    train_in = tset[0][:nread[k],:]


    # This is a little bit of work -- 1 of N encoding
    # Make sure you understand how it does it
    train_tgt = np.zeros((nread[k],10))
    for i in range(nread[k]):
        train_tgt[i,tset[1][i]] = 1
    
    test_in = teset[0][:nread[k],:]
    test_tgt = np.zeros((nread[k],10))
    for i in range(nread[k]):
        test_tgt[i,teset[1][i]] = 1
    
    # We will need the validation set
    valid_in = vset[0][:nread[k],:]
    valid_tgt = np.zeros((nread[k],10))
    for i in range(nread[k]):
        valid_tgt[i,vset[1][i]] = 1
    
    for i in [1,2,5,10,20]:
        print ("----- "+str(i))
        net = mlp.mlp(train_in,train_tgt,i,outtype='softmax')
        net.earlystopping(train_in,train_tgt,valid_in,valid_tgt,0.1)
        net.confmat(test_in,test_tgt)

----- 1
1
Iteration:  0  Error:  92.58365211967143
2
Iteration:  0  Error:  87.60880802764225
3
Iteration:  0  Error:  85.53653828978545
4
Iteration:  0  Error:  83.7769863381827
5
Iteration:  0  Error:  82.10037250687157
6
Iteration:  0  Error:  80.5296150436248
7
Iteration:  0  Error:  79.29247726689793
8
Iteration:  0  Error:  78.43227674740963
9
Iteration:  0  Error:  77.81624785529544
10
Iteration:  0  Error:  77.3328145954395
Stopped 85.02736876622974 84.89583843878987 84.79612880289437
Confusion matrix is:
[[17.  0.  4. 13.  8. 11.  6.  2.  4.  6.]
 [ 0. 28.  3.  1.  5.  4.  6.  8.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  4.  2.  7.  1.  6.  9.  2.  2.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  5.  0.  8.  4.  2.  5.  3. 12.]]
Percentage Correct:  33.0
----- 2
1
Iteration:  0 