In [27]:

import numpy as np
from sklearn.metrics import confusion_matrix,precision_score


y_true = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,\
          2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,0,0,0,0,0,0,0,0,\
          1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2]
y_pred = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,\
          2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,2,2,2,2,2,2,\
          0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,1,1]


cm =confusion_matrix(y_true, y_pred, labels=[0,1,2])

print(cm)

tp0 = cm[0][0]
fp0 = cm[1][0]+cm[2][0]
tn0 = cm[1][1]+cm[1][2]+cm[2][1]+cm[2][2]
fn0 = cm[0][1]+cm[0][2]
total = sum(sum(cm))



print('\nTrue positive 0 = ', round(tp0/total*100,2),"%")
print('False positive 0 = ', round(fp0/total*100,2),"%")
print('True negative 0  = ', round(tn0/total*100,2),"%")
print('False negative 0 = ', round(fn0/total*100,2),"%")

tp1 = cm[1][1]
fp1 = cm[0][1]+cm[2][1]
tn1 = cm[0][0]+cm[0][2]+cm[2][0]+cm[2][2]
fn1 = cm[1][0]+cm[1][2]


print('\nTrue positive 1 = ', round(tp1/total*100,2),"%")
print('False positive 1 = ', round(fp1/total*100,2),"%")
print('True negative 1 = ', round(tn1/total*100,2),"%")
print('False negative 1 = ', round(fn1/total*100,2),"%")

tp2 = cm[2][2]
fp2 = cm[0][2]+cm[1][2]
tn2 = cm[0][0]+cm[0][1]+cm[1][0]+cm[1][1]
fn2 = cm[2][0]+cm[2][1]


print('\nTrue positive 2 = ', round(tp2/total*100,2),"%")
print('False positive 2 = ', round(fp2/total*100,2),"%")
print('True negative 2 = ', round(tn2/total*100,2),"%")
print('False negative 2 = ', round(fn2/total*100,2),"%")

MAP = (tp0+tp1+tp2)/(tp0+tp1+tp2+fp0+fp1+fp2)
MAR = ((tp0/(fp0+tp0))+(tp1/(fp1+tp1))+(tp2/(fp2+tp2)))/3


print("\nMicro-Averaged Precision = ", round(MAP,4))
print("Macro-Averaged Recall = ", round(MAR,4))










[[20  4  6]
 [ 4 16  2]
 [12  2 32]]

True positive 0 =  20.41 %
False positive 0 =  16.33 %
True negative 0  =  53.06 %
False negative 0 =  10.2 %

True positive 1 =  16.33 %
False positive 1 =  6.12 %
True negative 1 =  71.43 %
False negative 1 =  6.12 %

True positive 2 =  32.65 %
False positive 2 =  8.16 %
True negative 2 =  44.9 %
False negative 2 =  14.29 %

Micro-Averaged Precision =  0.6939
Macro-Averaged Recall =  0.6943
